### PR TITLE
[WIP] feature: better track handling

### PR DESCRIPTION
**Pull request by tkurki**
This PR changes track http interface api and implementation.

Navigation.position  is stored once per minute to an SQLite db with
geohashing. When serving track data first retrieve a list of track
periods by bounding box and then retrieve positions for those
periods from InfluxDb with grouping suitable for the bounding box
size.

The track interface returns GeoJSON FeatureCollections with name, starttime and endtime metadata in individual track feature's properties.

Depends on https://github.com/SignalK/signalk-server-node/pull/291

Preliminary UI available at https://github.com/vokkim/tuktuk-chart-plotter/pull/10

Todo: 
- [ ] add index to sqlite database
- [ ] minimise trackdata table: only timestamp and hash really needed

### CODE REVIEW

**Comment by sbender9** [comment]
Maybe `use app.config.configPath` for the path of the db?

**Comment by sbender9** [comment]
I'm also concerned about that db growing out of control. Is there any way to limit it?

**Comment by tkurki** [comment]
I am not. 

I'd be more worried about InfluxDb. Position is stored in InfluxDb once per second, in SQLite db once per minute. And this is not counting all the other data that goes into InfluxDb.

My trackdb of 24844 points (~414 hours) is 1.1 Megabytes, so a year of round the clock tracking would produce ~21 MB. And this is with the current schema, I expect that to go down when I remove the not used position string column.

If this becomes an issue we can partition the sqlite tables one per year, so the user can swap them out on a reasonable granularity if needed. 

I haven't looked into InfluxDb storage, it is probably way way more trouble to prune that database.

I have yet to test this on a RPi performancewise.

Thanks for giving it a spin, really appreciate a second pair of eyes!

**Comment by sbender9** [comment]
I missed that it was only once per minute. 

You can setup default retention policies in influxdb to keep that db down.

**Comment by tkurki** [comment]
- [ ] make db location relative to `app.config.configPath`

**Comment by tkurki** [comment]
- [ ] index for geohash search
- [ ] retrieve by id

**Pull request closed without merging**
